# Welcome to Jekyll!
#

# Site settings
title: Spectral
description: |
  Another fine responsive  
  site template freebie  
  crafted by [HTML5 UP](http://html5up.net)
owner: Chen Mingxin # or company name
first_published: 2019 # if migrating another site, the year of your first publish
email: mxchen1997@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
social:
  github: https://github.com/owemmx
  linkedin-square: https://linkedin.com/in/chenmingxin
  facebook-official: https://facebook.com/<username>
  google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
